

/* Create database */
CREATE DATABASE ordersystem WITH ENCODING 'UTF8' LC_COLLATE 'en_US.utf8' LC_CTYPE 'en_US.utf8' TEMPLATE template0;

/* Create 4 tables */
CREATE TYPE colors AS ENUM('Cherry', 'Natural Ash', 'White Ash', 'Red Oak', 'Natural Oak', 'Walnut');

CREATE TABLE PRODUCT(
	PRODUCT_ID INTEGER NOT NULL, 
	PRODUCT_DESCRIPTION VARCHAR(50), 
	PRODUCT_FINISH colors,
	STANDARD_PRICE DECIMAL(8,2),
	CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID));

CREATE TABLE CUSTOMER(
	CUSTOMER_ID INTEGER NOT NULL, 
	CUSTOMER_NAME VARCHAR(25) NOT NULL, 
	CUSTOMER_ADDRESS VARCHAR(30),
	CITY VARCHAR(20),
	POSTAL_CODE VARCHAR(9),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE ORDERT(
    ORDER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CUSTOMER_ID INTEGER NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

CREATE TABLE ORDER_LINE(
    ORDER_ID INTEGER NOT NULL, 
    PRODUCT_ID INTEGER NOT NULL, 
    ORDERED_QUANTITY INTEGER,
    CONSTRAINT ORDER_LINE_PK PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT ORDER_LINE_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERT(ORDER_ID),
    CONSTRAINT ORDER_LINE_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));
