SELECT 
  SUM(P.STANDARD_PRICE * OL.ORDERED_QUANTITY) AS TOTAL_PAYMENT
FROM ORDERT O
JOIN 
  ORDER_LINE OL ON O.ORDER_ID = OL.ORDER_ID
JOIN 
  PRODUCT P ON OL.PRODUCT_ID = P.PRODUCT_ID
WHERE 
  O.ORDER_ID = 3
GROUP BY 
  O.ORDER_ID;