WITH PRODUCT_ORDERED AS (
	SELECT PRODUCT_ID, COUNT(*) AS ORDERED_COUNT FROM ORDER_LINE
	GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID, P.PRODUCT_DESCRIPTION 
FROM PRODUCT P
JOIN (
	SELECT PRODUCT_ID FROM PRODUCT_ORDERED
	WHERE ORDERED_COUNT = (SELECT MAX(ORDERED_COUNT) FROM PRODUCT_ORDERED)
) AS MOST_ORDERED 
ON P.PRODUCT_ID = MOST_ORDERED.PRODUCT_ID;