SELECT P.PRODUCT_ID, P.PRODUCT_DESCRIPTION 
FROM PRODUCT P
JOIN (
	SELECT PRODUCT_ID, SUM(ORDERED_QUANTITY) AS ORDERED_COUNT FROM ORDER_LINE
	GROUP BY PRODUCT_ID
	ORDER BY ORDERED_COUNT DESC
	LIMIT 1
) AS MOST_ORDERED 
ON P.PRODUCT_ID = MOST_ORDERED.PRODUCT_ID;